//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comp1.Public.ReaderFile.ReaderWriteFile02 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class ReaderFileSettings02 : global::System.Configuration.ApplicationSettingsBase {
        
        private static ReaderFileSettings02 defaultInstance = ((ReaderFileSettings02)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ReaderFileSettings02())));
        
        public static ReaderFileSettings02 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MainFilePath {
            get {
                return ((string)(this["MainFilePath"]));
            }
            set {
                this["MainFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public int ReaderLength {
            get {
                return ((int)(this["ReaderLength"]));
            }
            set {
                this["ReaderLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public int StopLength {
            get {
                return ((int)(this["StopLength"]));
            }
            set {
                this["StopLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CreateInFolder {
            get {
                return ((bool)(this["CreateInFolder"]));
            }
            set {
                this["CreateInFolder"] = value;
            }
        }
    }
}
